### ISSUE TITLE
VanityGaps not showing in the finalized config

### ISSUE THREAD

**Issue by mafsi** [bakkeby/flexipatch-finalizer#12]
If someone check vanity gaps to be active and build the dwm, when finalize with flexipatch is not showing in the new config.

**Comment by bakkeby** [comment]
How do you "check vanity gaps to be active"?

**Comment by mafsi** [comment]
I activate the patch in `patches.def.h`:
```
#define VANITYGAPS_PATCH 1
```

In config.def.h there is a code for this
```
#if VANITYGAPS_PATCH
static const unsigned int gappih         = 20;  /* horiz inner gap between windows */
static const unsigned int gappiv         = 10;  /* vert inner gap between windows */
static const unsigned int gappoh         = 10;  /* horiz outer gap between windows and screen edge */
static const unsigned int gappov         = 30;  /* vert outer gap between windows and screen edge */
static const int smartgaps_fact          = 1;   /* gap factor when there is only one client; 0 = no gaps, 3 = 3x outer gaps */
#endif // VANITYGAPS_PATCH
```
when finalize dwm this code is not present in the config.def.h

`./flexipatch-finalizer.sh -r -d ../path-to-dwm/ -o ../dwm-build`

**Comment by bakkeby** [comment]
The `patches.def.h` is the _default_ patches file, similarly how `config.def.h` is the default configuration file.

When you run `make` the first time then the default configuration files are copied to `config.h` and `patches.h`, which are your personal configuration files that you can modify to your liking.

flexipatch-finalizer will finalize the build based on your personal settings in patches.h. To finalize using the default `patches.def.h` would not make much sense.

**Comment by mafsi** [comment]
Let me see if I understood correctly:
1. we use in your scripts only `patches.h` , `not patches.def.h`
2. No sense to use `config.def.h`, only `config.h`

The problem is that if I use only `config.h` this file is always regenerated after a patch, therefore I always used `config.def.h` and remove after each compilation `config.h`. For the patching I used only `patches.def.h`

**Comment by bakkeby** [comment]
Why would you think that config.h is always regenerated after a patch?

**Comment by mafsi** [comment]
> Why would you think that config.h is always regenerated after a patch?

I guess because is patched all the time. It seems that I misunderstood completely the workflow. I saw a lot of videos on youtube when people patched dwm or st, and keeping config.h will cause errors

**Comment by bakkeby** [comment]
If you use tools like `patch` or `git apply` then a patch can only change the default config.def.h. This is something that everyone is caught out with in the beginning. YouTubers tend to be confused about this and will recommend misguided things like editing config.def.h and to add instructions in the Makefile to delete config.h every time you compile.

A simple diff between the two files should be enough to see what is missing in config.h in such case.

The general recommendation, imho, would be to always patch manually by hand. It is tedious, frustrating and time consuming, but at the end of the day it gives you an opportunity to learn the code and what the patches change to give the desired behaviour.

**Comment by mafsi** [comment]
Thanks a lot for the advice. I'll use your flexipatch, for faster deploy a pc until I'll make patch manually. Keep doing the great job you do now!
