### ISSUE TITLE
Q: Ignoring git files

### ISSUE THREAD

**Issue by YsnSen** [bakkeby/flexipatch-finalizer#7]
Is it possible to pass a flag when finalizing a flexi build to ignore git files?

**Comment by bakkeby** [comment]
Hi @KirliAdam,

the flexipatch-finalizer doesn't actually do anything with git files.

The code from the source directory (`-d <dir>`) is copied to the output directory (`-o <dir>`) ignoring any hidden files (e.g. .git). If you actually need this then you can just copy the .git directory from the source directory.

Does that make sense?

\
Thanks,

-Stein

**Comment by YsnSen** [comment]
For some reason hidden files are copied during operation. Or maybe I am missing something related to git not flexipatch-finalizer.
I have forked dwm-flexipatch and changed default tag count to 7 and did little modifications to config.def.h file and synced with upstream. After using the flexipatch-finalizer this is the result.
https://i.imgur.com/7zTtOvj.gif

Sorry about my English and thanks for your time and reply.

-Yasin

**Comment by bakkeby** [comment]
Most likely I'm mistaken. Probably it used to not copy .git files, but someone requested that being added in. I'll have a look.

Out of interest what is your use-case for using flexipatch-finalizer?

**Comment by YsnSen** [comment]
> Most likely I'm mistaken. Probably it used to not copy .git files, but someone requested that being added in. I'll have a look.
> 
> Out of interest what is your use-case for using flexipatch-finalizer?

I created a dwm repo for myself on github for easy installing software that I use. I plan to do it for other software too. I am new to linux arch. I find it easier to maintain like these if i am not mistaken. But I am open to suggestions.

Thank you.

-Yasin

**Comment by bakkeby** [comment]
Hi @KirliAdam,

I have obviously been fairly occupied with various things lately, sorry for the delay. I have added a flag `-g` to explicitly include .git (and .gitignore) files for those that actually want that. The script now deletes these by default.

Should someone prefer to always include the .git files like it used to then they can always set `KEEP_GITFILES=1` at the start of the script.

\
Thanks,

-Stein
