### ISSUE TITLE
script only copy files without make any changes

### ISSUE THREAD

**Issue by mrbooshehri** [bakkeby/flexipatch-finalizer#8]
after running the script `/flexipatch-finalizer.sh -r -d ../dwm-flexipatch -o ../my-dwm` the following output appears:

awk: line 5: illegal reference to local variable f
awk: line 12: illegal reference to local variable f
awk: line 19: illegal reference to local variable f
awk: line 21: illegal reference to local variable f
awk: line 22: illegal reference to local variable f

**Comment by bakkeby** [comment]
Hmm, what version of awk do you have?

**Comment by mrbooshehri** [comment]
This is output of `awk -W version`

mawk 1.3.4 20200120
Copyright 2008-2019,2020, Thomas E. Dickey
Copyright 1991-1996,2014, Michael D. Brennan

random-funcs:       srandom/random
regex-funcs:        internal
compiled limits:
sprintf buffer      8192
maximum-integer     2147483647

**Comment by bakkeby** [comment]
Ref. https://stackoverflow.com/questions/16921493/awk-illegal-reference-to-array-a retrieving the length of an array is apparently a GNU extension to awk and is not posix compliant.

I just pushed some proposed changes. Could you try this and let me know if there are any other errors?

**Comment by mrbooshehri** [comment]
I made the changes and this is the result:

awk: line 36: regular expression compile failed (missing operand)
* Skip duplicates *
awk: line 53: regular expression compile failed (missing operand)
* Read patches.h and store patch settings in the patches associative array *

**Comment by bakkeby** [comment]
That was painful to investigate.

The errors you saw was because mawk does not support `/* .. */` comments, which was trivial to sort out, but I then found that it didn't produce the right output / results.

Eventually I worked out that it was due to a line like this:
```awk
			do_print[++level] = do_print[level]
```

which had to be written like this instead:
```awk
			level++;
			do_print[level] = do_print[level-1]
```

**Comment by mrbooshehri** [comment]
Thanks the problem solved.
